shellEmulator: true

trustPolicy: no-downgrade

packages:
  - ./
  - ./packages/*
  - samples/*
  - samples/monorepo-vitest-workspace/packages/*

catalog:
  '@playwright/test': ^1.42.1
  '@types/chai': ^5.2.2
  '@types/micromatch': ^4.0.6
  '@types/mocha': ^10.0.6
  '@types/node': ^24.0.0
  '@types/prompts': ^2.4.9
  '@types/semver': ^7.3.9
  '@types/which': ^3.0.3
  '@types/ws': ^8.5.10
  '@vscode/test-cli': ^0.0.6
  '@vscode/test-electron': ^2.3.9
  '@vscode/vsce': ^3.1.0
  '@vue/reactivity': ^3.2.33
  acorn: ^8.12.0
  acorn-walk: ^8.3.3
  birpc: 2.4.0
  bumpp: ^10.1.1
  chai: ^5.1.0
  changelogithub: ^13.15.0
  execa: ^8.0.1
  find-up: ^7.0.0
  get-port: ^6.1.2
  istanbul-to-vscode: ^2.1.0
  micromatch: ^4.0.5
  mighty-promise: ^0.0.8
  mocha: ^10.3.0
  pathe: ^1.1.2
  picocolors: ^1.0.0
  prompts: ^2.4.2
  semver: ^7.3.5
  tsdown: ^0.20.3
  tsx: ^4.7.1
  typescript: ^5.6.2
  which: ^4.0.0
  ws: ^8.16.0
catalogs:
  latest:
    '@types/picomatch': ^4.0.2
    '@vitest/browser': ^4.1.0-beta.3
    '@vitest/browser-playwright': ^4.1.0-beta.3
    '@vitest/coverage-istanbul': ^4.1.0-beta.3
    '@vitest/coverage-v8': ^4.1.0-beta.3
    '@vitest/utils': ^4.1.0-beta.3
    picomatch: ^4.0.3
    vite: ^7.2.6
    vitest: ^4.1.0-beta.3

  v3:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/runner': ^3.2.4
    '@vitest/utils': ^3.2.4
    vite: ^7.2.6
    vitest: ^3.2.4
