packages:
  - ./
  - ./packages/*
  - samples/*
  - samples/monorepo-vitest-workspace/packages/*

catalog:
  '@vitest/browser-playwright': ^4.0.0-beta.15
  '@vitest/browser-webdriverio': ^4.0.0-beta.15
  '@vitest/coverage-istanbul': ^4.0.0-beta.15
  '@vitest/coverage-v8': ^4.0.0-beta.15
  '@vitest/runner': ^4.0.0-beta.15
  '@vitest/utils': ^4.0.0-beta.15
  vite: ^7.1.0
  vitest: ^3.2.2
