packages:
  - ./
  - ./packages/*
  - samples/*
  - samples/monorepo-vitest-workspace/packages/*

catalogs:
  latest:
    '@vitest/browser': ^4.0.14
    '@vitest/browser-playwright': ^4.0.14
    '@vitest/coverage-istanbul': ^4.0.14
    '@vitest/coverage-v8': ^4.0.14
    '@vitest/runner': ^4.0.14
    '@vitest/utils': ^4.0.14
    vite: ^7.2.6
    vitest: ^4.0.14

  v3:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-istanbul': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/runner': ^3.2.4
    '@vitest/utils': ^3.2.4
    vitest: ^3.2.4
