packages:
  - ./
  - samples/*
  - samples/monorepo-vitest-workspace/packages/*

catalog:
  '@vitest/browser': ^3.2.2
  '@vitest/coverage-istanbul': ^3.2.2
  '@vitest/coverage-v8': ^3.2.2
  '@vitest/runner': ^3.2.2
  '@vitest/utils': ^3.2.2
  vite: ^6.3.5
  vitest: ^3.2.2
