packages:
  - ./
  - ./packages/*
  - samples/*
  - samples/monorepo-vitest-workspace/packages/*

catalog:
  '@vitest/browser': ^4.0.3
  '@vitest/browser-playwright': ^4.0.3
  '@vitest/coverage-istanbul': ^4.0.3
  '@vitest/coverage-v8': ^4.0.3
  '@vitest/runner': ^4.0.3
  '@vitest/utils': ^4.0.3
  vite: ^7.1.0
  vitest: ^4.0.3
