packages:
  - ./
  - samples/*
  - '!samples/monorepo-vitest-workspace'
  - '!samples/monorepo-nx'
  - '!samples/monorepo-no-root'
  - '!samples/monorepo'

catalog:
  vite: ^6.3.5
  vitest: ^3.2.2
  '@vitest/coverage-v8': ^3.2.2
  '@vitest/coverage-istanbul': ^3.2.2
  '@vitest/runner': ^3.2.2
  '@vitest/utils': ^3.2.2
  '@vitest/browser': ^3.2.2
